### ISSUE TITLE
Removed from CRAN?

### ISSUE THREAD

**Issue by schoewed** [sboysel/fredr#76] opened 2020-05-08 13:57 UTC
Hey! Just curious why this was recently pulled from the CRAN repo? I downloaded the devtools version  but was curious what happened. Let me know, seems like a great package!

**Comment by rcberg** [comment] 2020-05-08 19:54
not updated for R 4.0.0 it seems :\

**Comment by sboysel** [comment] 2020-05-14 21:28
@schoewed Unfortunately yes.  I'm taking a look at it tonight so hopefully I can resubmit and have it back on CRAN within a few days.  Duplicate of #75 so I'll redirect any concern to that issue.

**Closed by sboysel** 2020-05-14 21:28 UTC
